include = Dir('#/rebuild/include')
env = Environment(CCFLAGS='-std=c++11', CPPPATH=[include, '#'])
env.ParseConfig("root-config --cflags --glibs")

print env['CPPPATH']	


## Generate Root Dictionary File 
cintBuilder = Builder(action = 'rootcint -f $TARGET -c $SOURCES')
env.Append(BUILDERS= {'cint': cintBuilder})

pADict = env.cint('PulseAnalysisDict.cxx', ['#/rebuild/include/PulseAnalysis.h', '#/rebuild/include/PulseAnalysisLinkDef.h'])
PSbuffer = env.cint('PSbuffer.cxx', ['#/rebuild/include/PSbuffer.h'])

Clean(pADict, 'PulseAnalysisDict.h')
Clean(PSbuffer, 'PSbufferDict.h')

paDictObj = env.SharedLibrary(pADict)
PSbufferDictObj = env.SharedLibrary(PSbuffer)


pR = env.SharedLibrary('picoReader', ['PicoReader.cc'])
pA = env.SharedLibrary('PulseAnalysis', ['PulseAnalysis.cc', 'PulseAnalysis.analysis.cc', 'PulseAnalysis.display.cc', paDictObj, pR, PSbufferDictObj])
env.Install('#/rebuild/install', [pA, paDictObj])
env.Install('#/rebuild/install', [PSbufferDictObj])
